### ISSUE TITLE
Verifying the SDN feature in GINI

### ISSUE THREAD

**Issue by anrl** [citelab/gini5#12]
We have SDN in GINI.

This feature was working with UMLs. Since we migrated to Docker, this feature was not exercised.
I would like to get it tested and verified very soon.

**Comment by trungams** [comment]
WIP in branch ovs. The most recent commit is: 07fadf1ae072df1c0c3261ea6db0fd7f97b47973

**Comment by trungams** [comment]
TODOs:
- [x] Resolve the Permission denied error when running `ovs-docker`
- [x] During compilation, take notes of what OVS is connected to an OpenFlow Controller in a network
- [x] Connect them on the backend using `ovs-vsctl set-controller switch-name`

**Comment by trungams** [comment]
Regarding 1: normal users don't have the permission to write PID file in /var/run. The following thread suggests creating /var/run/netns manually and chown/chmod that directory so that the current users can read/write to it

https://serverfault.com/questions/159334/what-permission-to-write-pid-file-in-var-run

**Comment by trungams** [comment]
Refer to this example on how to load/unload event handlers, and how to clear flow tables in connected switches

https://github.com/hip2b2/poxstuff/blob/master/of_sw_tutorial_oo.py

**Comment by trungams** [comment]
Resolved in #46
