### ISSUE TITLE
Cloud support in GINI

### ISSUE THREAD

**Issue by anrl** [citelab/gini5#7]
It would be nice to have Cloud support in GINI.
We have Docker swarm available for drag and drop from the side menu.

**Comment by trungams** [comment]
Here's the to-do list at the moment, I will update it as we go:
- [x] add a cloud component on the front-end
- [x] add the corresponding to gini_components.py on back-end
- [x] add routing scheme for the cloud component. if there's a specific router/load balancer to be exposed to user, how should we design it
- [ ] ~~use docker swarm to start and manage the cloud. Note that we're restricting to one cloud instance per topology, since the number of physical host is limited.~~

**Comment by trungams** [comment]
done
